name: 'Terraform Plan'

on:
  push:
    branches: [ '**' ]  # Triggered on push to any branch
    paths:
      - '*/**.tf'  # Any Terraform file in any subdirectory
      - '*/**.tfvars'  # Any Terraform state file in any subdirectory
      - '.github/workflows/plan.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - '*/**.tf'  # Any Terraform file in any subdirectory
      - '*/**.tfvars'  # Any Terraform state file in any subdirectory
      - '.github/workflows/plan.yml'
    types: [opened, synchronize, reopened]

env:
  TF_VERSION: '1.5.7'  # Specify Terraform version
  AWS_REGION: 'ap-southeast-1'  # Update with your AWS region

jobs:
  check:
    name: fetch modified directories
    output: 
      changed_folders: ${{ steps.check.outputs.folders }}
      run_tf: ${{ steps.check.outputs.run_tf }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-dept: 0
         
      - name: Get terraform plan apply folder path
        id: check
        run: |
          echo "Checking for modified directories..."
          git fetch --prune --unshallow
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.tf$' | sed 's|/[^/]*\.tf$||' | sort -u > folders.txt
          if [ -s folders.txt ]; then
            echo "Modified directories:"
            cat folders.txt
            echo "::set-output name=folders::$(cat folders.txt)"
            echo "::set-output name=run_tf::true"
          else
            echo "No modified directories found."
            echo "::set-output name=run_tf::false"
          fi